In [2]:
import numpy as np
import copy

In [3]:
example_vectors = [[1, -1, 1, -1, 1, -1], [-1, 1, -1, 1, -1, 1], [1, 1, 1, 1, 1, 1]]
test_vectors = [[1, -1, 1, 1, -1, 1], [-1, 1, 1, -1, 1, -1], [1, 1, 1, -1, -1, -1], [-1, -1, -1, 1, 1, 1], 
                [1, 1, 1, 1, 1, 1], [-1, -1, 1, -1, -1, -1], [-1, -1, -1, 1, -1, -1], [1, 1, -1, -1, 1, 1],
                [1, 1, -1, 1, 1, 1], [1, 1, 1, -1, 1, 1]]



In [4]:
# initial weights
weights = []
for i in range(len(example_vectors)):
    w = [number / 2 for number in example_vectors[i]]
    weights.append(w)
weights = np.array(weights).transpose()
print(weights)

[[ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]


In [5]:
# initial biases
bias = [3, 3, 3]
y_in = np.zeros((3,1))
y = np.zeros((3,1))

In [6]:
def activation(x):
    if x >= 0:
        return x
    return 0

e = 0.1

In [9]:
for i in range(len(test_vectors)):
    print("Test Vector Number: ", i)
    for j in range(len(example_vectors)):
        y_in[j] = bias[j] + np.sum(np.array(weights).transpose()[j] * test_vectors[i])
        
    y = copy.deepcopy(y_in)
    
    y_old = np.array(y.copy())
    y_new = []
    count = 0
    while True: 
#         print('Iteration {} - activations = {}'.format(count, [ '%.2f' % elem for elem in y_old ]))
        temp = np.sum(y_old)
        for i in range(len(y_old)): 
            value = y_old[i] - e * temp + e * y_old[i]
            y_new.append(activation(value))
        y_old = y_new.copy() 
        count += 1
        if np.sum(y_new) == max(y_new): 
            break
        y_new = []

#     print('Iteration {} - activations = {}'.format(count, [ '%.2f' % elem for elem in y_new ]))


    i=0
    while y_new[i]==0:
        i=i+1
    print ("Winning neuron : ", y[i])
    print ("Winning neuron number : ", i+1)
    print()
        

Test Vector Number:  0
Winning neuron :  [4.]
Winning neuron number :  3

Test Vector Number:  1
Winning neuron :  [4.]
Winning neuron number :  1

Test Vector Number:  2
Winning neuron :  [4.]
Winning neuron number :  1

Test Vector Number:  3
Winning neuron :  [4.]
Winning neuron number :  2

Test Vector Number:  4
Winning neuron :  [6.]
Winning neuron number :  3

Test Vector Number:  5
Winning neuron :  [4.]
Winning neuron number :  1

Test Vector Number:  6
Winning neuron :  [4.]
Winning neuron number :  2

Test Vector Number:  7
Winning neuron :  [4.]
Winning neuron number :  3

Test Vector Number:  8
Winning neuron :  [5.]
Winning neuron number :  3

Test Vector Number:  9
Winning neuron :  [5.]
Winning neuron number :  3

